"""empty message

Revision ID: fd625ce87b34
Revises: 
Create Date: 2021-02-26 18:29:31.569923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd625ce87b34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.Column('hair_color', sa.String(length=20), nullable=True),
    sa.Column('skin_color', sa.String(length=20), nullable=True),
    sa.Column('eye_color', sa.String(length=20), nullable=True),
    sa.Column('birth_year', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('edited', sa.Date(), nullable=True),
    sa.Column('homeworld', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('planet',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('diameter', sa.Float(), nullable=True),
    sa.Column('rotation_period', sa.Float(), nullable=True),
    sa.Column('orbital_period', sa.Float(), nullable=True),
    sa.Column('gravity', sa.Float(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('climate', sa.String(length=20), nullable=True),
    sa.Column('terrain', sa.String(length=20), nullable=True),
    sa.Column('surface_water', sa.Integer(), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('edited', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('second_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicle',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=20), nullable=True),
    sa.Column('starship_class', sa.String(length=20), nullable=True),
    sa.Column('manufacturer', sa.String(length=20), nullable=True),
    sa.Column('cost_in_credits', sa.Integer(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('crew', sa.Float(), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('max_atmosphering_speed', sa.Float(), nullable=True),
    sa.Column('hyperdrive_rating', sa.Float(), nullable=True),
    sa.Column('mglt', sa.Integer(), nullable=True),
    sa.Column('cargo_capacity', sa.Integer(), nullable=True),
    sa.Column('consumables', sa.String(length=20), nullable=True),
    sa.Column('pilots', sa.Integer(), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('edited', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('favorites_characters',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.Integer(), nullable=True),
    sa.Column('character_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_uid'], ['characters.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('favorites_planets',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.Integer(), nullable=True),
    sa.Column('planet_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_uid'], ['planet.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('favorites_vehicles',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.Integer(), nullable=True),
    sa.Column('vehicle_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['vehicle_uid'], ['vehicle.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites_vehicles')
    op.drop_table('favorites_planets')
    op.drop_table('favorites_characters')
    op.drop_table('vehicle')
    op.drop_table('user')
    op.drop_table('planet')
    op.drop_table('characters')
    # ### end Alembic commands ###
